server:
  port: 8083

database:
  host: "localhost"
  port: 5432
  user: "admin"
  password: "admin123"
  dbname: "postgres"
  schema: "go_restaurant_orders_payment_service"
  sslmode: "disable"
rabbitmq:
  url: "amqp://admin:admin123@localhost:5672/"
  exchange: "order.events"
  routing_key: "order.status.updated"
order_service:
  connect_timeout: 5
  base_url: "http://localhost:8082"
  endpoint:
    get_order_by_id: "/orders/:id"